version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: testing_postgres
    environment:
      POSTGRES_DB: testing_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d # Мапим папку со скриптами. Автоматическое выполнение SQL-скриптов в алфавитном порядке при первом запуске
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d testing_system"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: testing_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    name: testing_network